<program> ::= { <statement> }

<statement> ::= <block-statement> | <expression-statement>

<block-statement> ::= INDENT { <statement> } DEDENT

<expression-statement> ::= <expression>

<expression> ::= <additive-expression>

<assignment-expression> ::= <variable> = <expression>

<additive-expression> ::= <multiplicative-expression> { ('+' | '-') <multiplicative-expression> }

<multiplicative-expression> ::= <primary-expression> { ('*' | '/') <primary-expression> }

<primary-expression> ::= <literal> | <grouped-expression>

<grouped-expression> ::= '(' <expression> ')'

<literal> ::= <integer-literal> | <float-literal> | <string-literal>

<integer-literal> ::= INT

<float-literal> ::= FLOAT

<string-literal> ::= STRING

<identifier> ::= STRING