version: '3'

env:
  VENV_DIR: 'env'

tasks:

  env:create:
    cmds:
      - python -m venv env

  env:activate:
    cmds:
      - source {{.VENV_DIR}}/bin/activate
    pre:
      - task: env:create

  deps:install:
    desc: Install the project dependencies
    cmds:
      - pip install -r requirements.txt
    pre:
      - task: env:activate

  deps:freeze:
    desc: Update the requirements.txt file
    cmds:
      - echo "" > requirements.txt
      - pip freeze >> requirements.txt
    pre:
      - task: env:activate

  fmt:
    desc: Format source and test files
    cmds:
      - autopep8 --in-place --recursive src tests
    pre:
      - task: env:activate

  lint:
    desc: Format source and test files
    cmds:
      - flake8 src tests
    pre:
      - task: env:activate

  test:
    desc: Run the unit tests
    cmds:
      - pytest
    pre:
      - task: env:activate

  run:
    desc: Run the main script
    cmds:
      - python3 src/main.py
    pre:
      - task: env:activate