name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Create virtual environment
        run: python -m venv env

      - name: Activate virtual environment
        run: source env/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Flake8
        run: pip install flake8

      - name: Install Autopep8
        run: pip install autopep8

      - name: Format code
        run: autopep8 --in-place --recursive src tests

      - name: Lint code
        run: flake8 src tests

      - name: Run tests
        run: pytest

      - name: Run main script
        run: python src/main.py